#!/usr/bin/env bash
#
# baristaw — project-local launcher for the barista build tool.
#
# Reads the pinned barista version from `.barista/wrapper.properties`
# next to this script, downloads that version into a per-user cache on
# first use, verifies it against the recorded SHA-256 (if any), then
# execs the cached barista with whatever arguments you passed.
#
# Re-runs are zero-cost: the cached binary is reused as long as the
# pinned version on disk matches the cache layout.
#
# Generated by `barista wrapper`. Edit `.barista/wrapper.properties`
# (not this script) to change the pinned version or download URL.

set -euo pipefail

# ---------------------------------------------------------------------
# Locate this script and the sidecar properties file.
# ---------------------------------------------------------------------
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
props_file="${script_dir}/.barista/wrapper.properties"

if [ ! -f "${props_file}" ]; then
  echo "baristaw: missing ${props_file}" >&2
  echo "baristaw: re-run \`barista wrapper\` from the project root to regenerate." >&2
  exit 1
fi

# ---------------------------------------------------------------------
# Parse wrapper.properties — a tiny TOML subset:
#   key = "value"
# Quotes are required; comments (#) and blank lines are ignored.
# ---------------------------------------------------------------------
prop() {
  # $1 = key
  awk -v k="$1" '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }
    {
      sub(/[[:space:]]*=[[:space:]]*/, "=")
      n = index($0, "=")
      if (n == 0) next
      key = substr($0, 1, n - 1)
      val = substr($0, n + 1)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      gsub(/^"|"$/, "", val)
      if (key == k) { print val; exit }
    }
  ' "${props_file}"
}

version="$(prop version)"
distribution_url_template="$(prop distribution_url)"
checksum="$(prop checksum_sha256)"

if [ -z "${version}" ]; then
  echo "baristaw: \`version\` missing from ${props_file}" >&2
  exit 1
fi
if [ -z "${distribution_url_template}" ]; then
  echo "baristaw: \`distribution_url\` missing from ${props_file}" >&2
  exit 1
fi

# ---------------------------------------------------------------------
# Detect the host triple — used to substitute {target} into the URL.
# Matches the naming convention barista's release artifacts use.
# ---------------------------------------------------------------------
detect_target() {
  uname_s="$(uname -s)"
  uname_m="$(uname -m)"
  case "${uname_s}" in
    Linux)   os="unknown-linux-gnu" ;;
    Darwin)  os="apple-darwin" ;;
    *)
      echo "baristaw: unsupported host OS \`${uname_s}\`" >&2
      exit 1
      ;;
  esac
  case "${uname_m}" in
    x86_64|amd64) arch="x86_64" ;;
    arm64|aarch64) arch="aarch64" ;;
    *)
      echo "baristaw: unsupported host arch \`${uname_m}\`" >&2
      exit 1
      ;;
  esac
  printf '%s-%s' "${arch}" "${os}"
}
target="$(detect_target)"

# Substitute {version} and {target} into the URL template.
download_url="${distribution_url_template//\{version\}/${version}}"
download_url="${download_url//\{target\}/${target}}"

# ---------------------------------------------------------------------
# Resolve the per-user cache directory and check for a cached binary.
# ---------------------------------------------------------------------
cache_root="${BARISTA_USER_HOME:-${HOME}/.barista}/wrapper/${version}"
cached_bin="${cache_root}/barista"

mkdir -p "${cache_root}"

download() {
  url="$1"
  dest="$2"
  if command -v curl >/dev/null 2>&1; then
    curl --fail --location --silent --show-error --output "${dest}" "${url}"
  elif command -v wget >/dev/null 2>&1; then
    wget --quiet --output-document "${dest}" "${url}"
  else
    echo "baristaw: neither \`curl\` nor \`wget\` is available" >&2
    exit 1
  fi
}

verify_sha256() {
  file="$1"
  expected="$2"
  if command -v sha256sum >/dev/null 2>&1; then
    actual="$(sha256sum "${file}" | awk '{print $1}')"
  elif command -v shasum >/dev/null 2>&1; then
    actual="$(shasum -a 256 "${file}" | awk '{print $1}')"
  else
    echo "baristaw: no sha256 tool found; skipping checksum verification" >&2
    return 0
  fi
  if [ "${actual}" != "${expected}" ]; then
    echo "baristaw: checksum mismatch for ${file}" >&2
    echo "baristaw:   expected ${expected}" >&2
    echo "baristaw:   actual   ${actual}" >&2
    return 1
  fi
}

if [ ! -x "${cached_bin}" ]; then
  tmp_dir="$(mktemp -d "${cache_root}/dl.XXXXXX")"
  trap 'rm -rf "${tmp_dir}"' EXIT
  archive="${tmp_dir}/barista.tar.gz"

  echo "baristaw: fetching barista ${version} for ${target}" >&2
  download "${download_url}" "${archive}"

  if [ -n "${checksum}" ]; then
    verify_sha256 "${archive}" "${checksum}"
  fi

  tar -xzf "${archive}" -C "${tmp_dir}"

  # The archive may unpack `barista` either at its root or one
  # subdirectory deep; tolerate both layouts.
  if [ -x "${tmp_dir}/barista" ]; then
    mv "${tmp_dir}/barista" "${cached_bin}"
  else
    found="$(find "${tmp_dir}" -type f -name barista -perm -u+x 2>/dev/null | head -n1)"
    if [ -z "${found}" ]; then
      echo "baristaw: barista binary not found inside ${archive}" >&2
      exit 1
    fi
    mv "${found}" "${cached_bin}"
  fi
  chmod +x "${cached_bin}"
  rm -rf "${tmp_dir}"
  trap - EXIT
fi

exec "${cached_bin}" "$@"
