@ECHO OFF
@REM baristaw.cmd — project-local launcher for the barista build tool.
@REM
@REM Reads the pinned barista version from .barista\wrapper.properties
@REM next to this script, downloads that version into a per-user cache
@REM on first use, verifies its SHA-256 (if one is recorded), and execs
@REM the cached barista with the arguments you passed.
@REM
@REM Generated by `barista wrapper`. Edit .barista\wrapper.properties
@REM (not this script) to change the pinned version or download URL.

SETLOCAL ENABLEDELAYEDEXPANSION

SET "SCRIPT_DIR=%~dp0"
SET "PROPS_FILE=%SCRIPT_DIR%.barista\wrapper.properties"

IF NOT EXIST "%PROPS_FILE%" (
  ECHO baristaw: missing %PROPS_FILE% 1>&2
  ECHO baristaw: re-run ^`barista wrapper^` from the project root to regenerate. 1>&2
  EXIT /B 1
)

SET "VERSION="
SET "DIST_URL="
SET "CHECKSUM="

FOR /F "usebackq tokens=1,* delims==" %%A IN ("%PROPS_FILE%") DO (
  SET "_K=%%A"
  SET "_V=%%B"
  CALL :TRIM _K
  CALL :TRIM _V
  CALL :DEQUOTE _V
  IF /I "!_K!"=="version"           SET "VERSION=!_V!"
  IF /I "!_K!"=="distribution_url"  SET "DIST_URL=!_V!"
  IF /I "!_K!"=="checksum_sha256"   SET "CHECKSUM=!_V!"
)

IF "%VERSION%"=="" (
  ECHO baristaw: `version` missing from %PROPS_FILE% 1>&2
  EXIT /B 1
)
IF "%DIST_URL%"=="" (
  ECHO baristaw: `distribution_url` missing from %PROPS_FILE% 1>&2
  EXIT /B 1
)

@REM Detect host arch — Windows ships ARM64 + AMD64; pick the release artifact.
IF /I "%PROCESSOR_ARCHITECTURE%"=="ARM64" (
  SET "TARGET=aarch64-pc-windows-msvc"
) ELSE (
  SET "TARGET=x86_64-pc-windows-msvc"
)

CALL SET "DOWNLOAD_URL=%%DIST_URL:{version}=%VERSION%%%"
CALL SET "DOWNLOAD_URL=%%DOWNLOAD_URL:{target}=%TARGET%%%"

IF DEFINED BARISTA_USER_HOME (
  SET "BARISTA_HOME=%BARISTA_USER_HOME%"
) ELSE (
  SET "BARISTA_HOME=%USERPROFILE%\.barista"
)
SET "CACHE_ROOT=%BARISTA_HOME%\wrapper\%VERSION%"
SET "CACHED_BIN=%CACHE_ROOT%\barista.exe"

IF NOT EXIST "%CACHE_ROOT%" MKDIR "%CACHE_ROOT%"

IF NOT EXIST "%CACHED_BIN%" (
  ECHO baristaw: fetching barista %VERSION% for %TARGET% 1>&2
  SET "ARCHIVE=%CACHE_ROOT%\barista.tar.gz"
  PowerShell -NoProfile -Command "Invoke-WebRequest -UseBasicParsing -Uri '%DOWNLOAD_URL%' -OutFile '%ARCHIVE%'"
  IF ERRORLEVEL 1 (
    ECHO baristaw: download failed 1>&2
    EXIT /B 1
  )

  IF NOT "%CHECKSUM%"=="" (
    FOR /F "tokens=*" %%H IN ('PowerShell -NoProfile -Command "(Get-FileHash -Algorithm SHA256 '%ARCHIVE%').Hash.ToLower()"') DO SET "ACTUAL=%%H"
    IF /I NOT "!ACTUAL!"=="%CHECKSUM%" (
      ECHO baristaw: checksum mismatch 1>&2
      ECHO baristaw:   expected %CHECKSUM% 1>&2
      ECHO baristaw:   actual   !ACTUAL! 1>&2
      EXIT /B 1
    )
  )

  PowerShell -NoProfile -Command "tar -xzf '%ARCHIVE%' -C '%CACHE_ROOT%'"
  IF ERRORLEVEL 1 (
    ECHO baristaw: failed to extract %ARCHIVE% 1>&2
    EXIT /B 1
  )

  IF NOT EXIST "%CACHED_BIN%" (
    @REM Some archives nest the binary one level deep.
    FOR /R "%CACHE_ROOT%" %%F IN (barista.exe) DO (
      IF NOT "%%~fF"=="%CACHED_BIN%" MOVE /Y "%%~fF" "%CACHED_BIN%" >NUL
    )
  )

  DEL /Q "%ARCHIVE%" 2>NUL
)

"%CACHED_BIN%" %*
EXIT /B %ERRORLEVEL%

:TRIM
SET "_S=!%1!"
FOR /F "tokens=* delims= " %%T IN ("!_S!") DO SET "_S=%%T"
@REM strip trailing spaces
:_TRIM_TRAIL
IF "!_S:~-1!"==" " (
  SET "_S=!_S:~0,-1!"
  GOTO :_TRIM_TRAIL
)
SET "%1=!_S!"
EXIT /B 0

:DEQUOTE
SET "_S=!%1!"
IF "!_S:~0,1!"=="\"" SET "_S=!_S:~1!"
IF "!_S:~-1!"=="\"" SET "_S=!_S:~0,-1!"
SET "%1=!_S!"
EXIT /B 0
