// SPDX-License-Identifier: MIT OR Apache-2.0

// Integration-test target — workspace security lints are allowed
// here. Panic-on-misuse (`unwrap()`/`expect()`/`panic!`) is the
// documented contract for failing a test loudly.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::as_conversions
)]

//! Snapshot coverage for the conversational CLI surfaces that emit
//! their summary directly (not through the structured-output
//! renderer): the `barista dial-in` and `barista wrapper` stderr
//! summary lines, plus the global `--version` shape.
//!
//! These run the real `barista` binary as a subprocess
//! (`CARGO_BIN_EXE_barista`) against a hermetic temp directory so the
//! captured bytes are exactly what a user sees. The summaries are
//! emitted via `eprintln!` (see `cmd::dial_in::run` and
//! `cmd::wrapper::run`), so we snapshot stderr.
//!
//! # Why these were a gap
//!
//! `cmd_dial_in` / `cmd_wrapper` snapshot the *files* these commands
//! write (`config.toml`, `wrapper.properties`) but never the one-line
//! summary printed to the terminal. `output/mod.rs` documents these
//! two surfaces as intentionally outside the structured-output story
//! for v0.1, so the renderer matrix doesn't reach them either. This
//! file pins them so a reword is caught in review.
//!
//! # Determinism
//!
//! - Tempdir paths in the summary are redacted to `<DIR>`.
//! - The dial-in concurrency value depends on host CPU count and is
//!   redacted to `<N>`.
//! - The `--version` string is release-dependent and redacted to
//!   `<VERSION>`; we still pin the `barista <version>` framing.

use std::path::Path;
use std::process::Command;

use tempfile::TempDir;

fn barista_bin() -> &'static str {
    env!("CARGO_BIN_EXE_barista")
}

/// `insta` settings that redact the host-specific bits out of the
/// dial-in / wrapper summary lines.
fn redacted(dir: &Path) -> insta::Settings {
    let mut s = insta::Settings::clone_current();
    // Absolute tempdir path -> stable placeholder. macOS tempdirs are
    // commonly symlinked through `/private`, so match both.
    let raw = dir.display().to_string();
    s.add_filter(&regex_escape(&raw), "<DIR>");
    s.add_filter(&format!("/private{}", regex_escape(&raw)), "<DIR>");
    // dial-in concurrency = host CPU count.
    s.add_filter(r"concurrency=\d+", "concurrency=<N>");
    s
}

/// Minimal regex escaper for the literal path filter (paths can
/// contain `.` and other metacharacters on some hosts).
fn regex_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if "\\.+*?()|[]{}^$".contains(c) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

// =====================================================================
// `barista dial-in --non-interactive` summary line.
// =====================================================================

#[test]
fn dial_in_summary_line() {
    let dir = TempDir::new().unwrap();
    let cfg = dir.path().join("config.toml");
    let out = Command::new(barista_bin())
        .args(["dial-in", "--non-interactive", "--output-path"])
        .arg(&cfg)
        .output()
        .expect("spawn barista dial-in");
    assert_eq!(
        out.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stderr = String::from_utf8(out.stderr).unwrap();
    redacted(dir.path()).bind(|| {
        insta::assert_snapshot!("dial_in_summary_line", stderr);
    });
}

// =====================================================================
// `barista wrapper` summary line.
// =====================================================================

#[test]
fn wrapper_summary_line() {
    let dir = TempDir::new().unwrap();
    let out = Command::new(barista_bin())
        .args(["--root"])
        .arg(dir.path())
        .args(["wrapper", "--version", "0.1.0-alpha.0"])
        .output()
        .expect("spawn barista wrapper");
    assert_eq!(
        out.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stderr = String::from_utf8(out.stderr).unwrap();
    redacted(dir.path()).bind(|| {
        insta::assert_snapshot!("wrapper_summary_line", stderr);
    });
}

// =====================================================================
// Global `--version` shape. Auto-generated by clap from the crate
// version; pin the `barista <version>` framing with the (release-
// dependent) version number redacted.
// =====================================================================

#[test]
fn global_version_shape() {
    let out = Command::new(barista_bin())
        .arg("--version")
        .output()
        .expect("spawn barista --version");
    assert_eq!(out.status.code(), Some(0));
    let stdout = String::from_utf8(out.stdout).unwrap();
    let mut settings = insta::Settings::clone_current();
    // `barista 0.1.0-alpha.0` -> redact the version token.
    settings.add_filter(r"barista \S+", "barista <VERSION>");
    settings.bind(|| {
        insta::assert_snapshot!("global_version_shape", stdout);
    });
}
