// Integration-test / example / benchmark target — workspace security
// lints are allowed here. Panic-on-misuse (`unwrap()`/`expect()`/`panic!`)
// is the documented contract for failing a test loudly.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::as_conversions
)]

//! Integration tests for `cmd::no_daemon` — the `--no-daemon`
//! escape hatch that routes Maven-vocabulary commands to a forked
//! upstream `mvn` process.
//!
//! Two flavors of test:
//!
//! 1. **Pure-Rust** tests that exercise the dispatch path with a
//!    fake `mvn` binary (a shell script that records its argv and
//!    exits with a configurable code). These are hermetic — they
//!    don't depend on the host's `mvn`.
//! 2. **Identity-output** tests that run the real system `mvn`
//!    against a 1-module Java project once via barista's
//!    `--no-daemon` path and once via a plain `mvn` invocation,
//!    then SHA-256-diff the produced `target/classes/*.class`
//!    files. These are skipped on hosts without `mvn` on `$PATH`
//!    so they don't block contributors who haven't set up a Java
//!    toolchain.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Locate the freshly-built `barista` binary in `target/debug/`
/// (or `target/release/` if that's where the test was launched
/// from). We can't use `assert_cmd` — it's not a workspace dep —
/// so we fall back to `CARGO_BIN_EXE_<name>`, which cargo sets
/// for integration tests of crates with `[[bin]]` targets.
fn barista_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_barista"))
}

/// Write a minimal 1-module Java project into `dir`:
///
/// - `pom.xml` declaring Java 17 source/target and zero deps.
/// - `src/main/java/example/Hello.java` with a single class.
///
/// The pom intentionally pins the maven-compiler-plugin so the
/// generated bytecode is deterministic across host JDKs (well,
/// modulo timestamps in non-`-parameters` mode — we still SHA the
/// `.class`, which is timestamp-free).
fn write_minimal_project(dir: &Path) {
    let pom = r#"<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>example</groupId>
  <artifactId>hello</artifactId>
  <version>0.1.0</version>
  <packaging>jar</packaging>
  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
      </plugin>
    </plugins>
  </build>
</project>
"#;
    let java = r#"package example;

public final class Hello {
    private Hello() {}
    public static String greet() {
        return "hello, barista";
    }
    public static void main(String[] args) {
        System.out.println(greet());
    }
}
"#;
    fs::write(dir.join("pom.xml"), pom).unwrap();
    let java_dir = dir.join("src").join("main").join("java").join("example");
    fs::create_dir_all(&java_dir).unwrap();
    fs::write(java_dir.join("Hello.java"), java).unwrap();
    // Pin Maven + Java versions for asdf users — the test moves
    // CWD off the workspace's own `.tool-versions`, and the asdf
    // shim refuses to dispatch without an explicit pin.
    fs::write(
        dir.join(".tool-versions"),
        "java temurin-21.0.4+7.0.LTS\nmaven 3.9.9\n",
    )
    .unwrap();
}

/// Create a fake `mvn` executable at `dir/bin/mvn` that records
/// its argv to `dir/argv.txt` and exits with `exit_code`. Returns
/// the directory to set as `MAVEN_HOME`.
#[cfg(unix)]
fn write_fake_mvn(dir: &Path, exit_code: i32) -> PathBuf {
    use std::os::unix::fs::PermissionsExt;
    let bin = dir.join("bin");
    fs::create_dir_all(&bin).unwrap();
    let mvn = bin.join("mvn");
    let log = dir.join("argv.txt");
    let script = format!(
        "#!/bin/sh\nprintf '%s\\n' \"$@\" > {}\nexit {}\n",
        shell_escape(log.to_str().unwrap()),
        exit_code,
    );
    fs::write(&mvn, script).unwrap();
    let mut perms = fs::metadata(&mvn).unwrap().permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&mvn, perms).unwrap();
    dir.to_path_buf()
}

#[cfg(unix)]
fn shell_escape(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Returns whether the host has a usable `mvn` on `$PATH`. Used
/// to gate the byte-equal identity tests.
fn host_has_mvn() -> bool {
    which::which("mvn").is_ok()
}

/// Run `barista --no-daemon <phase>` against `project_dir`.
fn run_barista_no_daemon(
    project_dir: &Path,
    phase: &str,
    extra_args: &[&str],
    env_overrides: &[(&str, &Path)],
) -> std::process::Output {
    let mut cmd = Command::new(barista_bin());
    cmd.arg("--no-daemon")
        .arg("--root")
        .arg(project_dir)
        .arg(phase);
    for a in extra_args {
        cmd.arg(a);
    }
    for (k, v) in env_overrides {
        cmd.env(k, v);
    }
    cmd.output().expect("spawn barista")
}

// ---------------------------------------------------------------
// 1) Hermetic pure-Rust tests against a fake mvn (no JDK needed).
// ---------------------------------------------------------------

#[cfg(unix)]
#[test]
fn no_daemon_forwards_phase_and_args_to_fake_mvn() {
    let td = tempfile::tempdir().unwrap();
    let project = td.path().join("project");
    fs::create_dir_all(&project).unwrap();
    fs::write(project.join("pom.xml"), b"<project/>").unwrap();

    let fake_home = td.path().join("fake-mvn");
    write_fake_mvn(&fake_home, 0);

    let out = run_barista_no_daemon(
        &project,
        "compile",
        &["-DskipTests", "-Dprop=value"],
        &[("MAVEN_HOME", fake_home.as_path())],
    );
    assert!(
        out.status.success(),
        "barista should exit 0 when fake mvn exits 0; stdout={} stderr={}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr),
    );

    let logged = fs::read_to_string(fake_home.join("argv.txt")).unwrap();
    let lines: Vec<&str> = logged.lines().collect();
    assert_eq!(
        lines,
        vec!["compile", "-DskipTests", "-Dprop=value"],
        "fake mvn should have been called with the phase + passthrough args verbatim",
    );
}

#[cfg(unix)]
#[test]
fn no_daemon_bubbles_nonzero_exit_code_from_fake_mvn() {
    let td = tempfile::tempdir().unwrap();
    let project = td.path().join("project");
    fs::create_dir_all(&project).unwrap();
    fs::write(project.join("pom.xml"), b"<project/>").unwrap();

    let fake_home = td.path().join("fake-mvn");
    write_fake_mvn(&fake_home, 42);

    let out = run_barista_no_daemon(
        &project,
        "verify",
        &[],
        &[("MAVEN_HOME", fake_home.as_path())],
    );
    assert_eq!(
        out.status.code(),
        Some(42),
        "barista should forward mvn's exit code verbatim; got {:?}",
        out.status.code(),
    );
}

#[cfg(unix)]
#[test]
fn no_daemon_emits_structured_error_when_mvn_missing() {
    let td = tempfile::tempdir().unwrap();
    let project = td.path().join("project");
    fs::create_dir_all(&project).unwrap();
    fs::write(project.join("pom.xml"), b"<project/>").unwrap();

    // Point MAVEN_HOME at a directory that doesn't contain
    // `bin/mvn`, AND clear PATH so the fallback can't find one
    // either.
    let bogus_home = td.path().join("bogus");
    fs::create_dir_all(&bogus_home).unwrap();

    let mut cmd = Command::new(barista_bin());
    cmd.arg("--no-daemon")
        .arg("--root")
        .arg(&project)
        .arg("compile")
        .env("MAVEN_HOME", &bogus_home)
        .env("PATH", "")
        .env_remove("PATHEXT");
    let out = cmd.output().expect("spawn barista");

    assert_eq!(
        out.status.code(),
        Some(2),
        "missing mvn should surface exit code 2; got {:?}",
        out.status.code(),
    );
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stderr.contains("BAR-NODAEMON-MVN-NOT-FOUND"),
        "stderr should contain the error code; got:\n{stderr}",
    );
    assert!(
        stderr.contains(bogus_home.to_str().unwrap()),
        "stderr should mention the MAVEN_HOME we tried; got:\n{stderr}",
    );
}

// ---------------------------------------------------------------
// 2) Identity-output [T] AC tests against the real system mvn.
// ---------------------------------------------------------------
//
// AC: "--no-daemon runs same workload (slower) and produces
// identical output". We assert this for the per-phase commands
// (compile here) by running both `mvn compile` directly and
// `barista compile --no-daemon` against the same 1-module project,
// then SHA-256-diffing every produced `target/classes/**/*.class`.
//
// Multi-module reactor parity (e.g. `barista verify --no-daemon`
// on a reactor with N modules) is intentionally out of scope here:
// the full lifecycle wiring lands in a subsequent milestone, and
// the byte-equal invariant for per-phase commands is exactly what
// the M4.2 T8 milestone scope asks for.

/// Compute the SHA-256 of `path`. No external dep — uses a
/// hand-rolled tiny SHA-256 to avoid adding `sha2` just for one
/// test target. We import the workspace's own SHA via the cache
/// crate instead.
fn sha256_file(path: &Path) -> String {
    // Use barista-cache's hash::sha256_hex if exposed; otherwise
    // shell out to `shasum`/`sha256sum` which are universally
    // available on macOS / Linux CI runners.
    if let Ok(out) = Command::new("shasum").args(["-a", "256"]).arg(path).output() {
        if out.status.success() {
            let s = String::from_utf8_lossy(&out.stdout);
            if let Some(hex) = s.split_whitespace().next() {
                return hex.to_string();
            }
        }
    }
    if let Ok(out) = Command::new("sha256sum").arg(path).output() {
        if out.status.success() {
            let s = String::from_utf8_lossy(&out.stdout);
            if let Some(hex) = s.split_whitespace().next() {
                return hex.to_string();
            }
        }
    }
    panic!("no shasum/sha256sum found on PATH; can't hash {path:?}");
}

/// Recursively collect every `.class` file under `dir`, relative
/// to `dir`. Sorted for determinism.
fn collect_class_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    if !dir.exists() {
        return out;
    }
    fn walk(d: &Path, base: &Path, out: &mut Vec<PathBuf>) {
        for entry in fs::read_dir(d).unwrap() {
            let entry = entry.unwrap();
            let p = entry.path();
            if p.is_dir() {
                walk(&p, base, out);
            } else if p.extension().and_then(|e| e.to_str()) == Some("class") {
                out.push(p.strip_prefix(base).unwrap().to_path_buf());
            }
        }
    }
    walk(dir, dir, &mut out);
    out.sort();
    out
}

#[test]
fn byte_equal_compile_against_real_mvn() {
    if !host_has_mvn() {
        eprintln!("skipping: no `mvn` on PATH");
        return;
    }

    let td_barista = tempfile::tempdir().unwrap();
    let td_mvn = tempfile::tempdir().unwrap();

    write_minimal_project(td_barista.path());
    write_minimal_project(td_mvn.path());

    // Run via barista --no-daemon.
    let out_b = Command::new(barista_bin())
        .arg("--no-daemon")
        .arg("--root")
        .arg(td_barista.path())
        .arg("compile")
        .output()
        .expect("spawn barista");
    assert!(
        out_b.status.success(),
        "barista --no-daemon compile failed: stdout={} stderr={}",
        String::from_utf8_lossy(&out_b.stdout),
        String::from_utf8_lossy(&out_b.stderr),
    );

    // Run via plain mvn.
    let out_m = Command::new("mvn")
        .arg("compile")
        .current_dir(td_mvn.path())
        .output()
        .expect("spawn mvn");
    assert!(
        out_m.status.success(),
        "mvn compile failed: stdout={} stderr={}",
        String::from_utf8_lossy(&out_m.stdout),
        String::from_utf8_lossy(&out_m.stderr),
    );

    let classes_b = td_barista.path().join("target").join("classes");
    let classes_m = td_mvn.path().join("target").join("classes");

    let files_b = collect_class_files(&classes_b);
    let files_m = collect_class_files(&classes_m);
    assert_eq!(
        files_b, files_m,
        "produced class-file sets differ:\n  barista: {files_b:?}\n  mvn:     {files_m:?}",
    );
    assert!(
        !files_b.is_empty(),
        "expected at least one .class produced; barista classes dir is empty: {classes_b:?}",
    );

    for rel in &files_b {
        let hash_b = sha256_file(&classes_b.join(rel));
        let hash_m = sha256_file(&classes_m.join(rel));
        assert_eq!(
            hash_b, hash_m,
            "SHA-256 mismatch on {rel:?}:\n  barista: {hash_b}\n  mvn:     {hash_m}",
        );
    }
}

// ---------------------------------------------------------------
// 3) Happy-path smoke test against the real system mvn (no diff).
// ---------------------------------------------------------------

#[test]
fn no_daemon_compile_smoke_against_real_mvn() {
    if !host_has_mvn() {
        eprintln!("skipping: no `mvn` on PATH");
        return;
    }

    let td = tempfile::tempdir().unwrap();
    write_minimal_project(td.path());

    let out = Command::new(barista_bin())
        .arg("--no-daemon")
        .arg("--root")
        .arg(td.path())
        .arg("compile")
        .output()
        .expect("spawn barista");

    assert!(
        out.status.success(),
        "barista compile --no-daemon should succeed; stdout={} stderr={}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr),
    );
    assert!(
        td.path()
            .join("target")
            .join("classes")
            .join("example")
            .join("Hello.class")
            .is_file(),
        "expected target/classes/example/Hello.class to be populated",
    );
}
