//! Rust bindings for the worker IPC protocol (`proto/barista/v1/worker.proto`).
//!
//! Generated by `prost-build` from `build.rs`; the generated source lives at
//! `$OUT_DIR/barista.v1.rs` and is `include!`d below. Downstream crates
//! consume the types via `barista_ipc::proto::*` or the convenience
//! re-exports at the crate root in `lib.rs`.
//!
//! ## Redacted `Debug` for credential-bearing types
//!
//! `prost`'s default `#[derive(Debug)]` would print decrypted password,
//! token, and SSH private-key bytes via `format!("{:?}", ...)`. That is a
//! credential-leakage surface (panic messages, error chains, structured
//! logging). The schema's `Credential`, `CredentialsEnvelope`, `SshKey`,
//! and `credential::Secret` types are tagged with `skip_debug` in
//! `build.rs` so prost emits no `Debug` impl for them; the manual impls
//! below redact every secret field.
//!
//! In tandem, the same types derive `zeroize::ZeroizeOnDrop` so the
//! decrypted bytes are scrubbed from memory the moment the message is
//! dropped. The transport-buffer half of this story (zeroing the on-wire
//! send/recv buffer) lands in M4.1 Task 5 (filesystem-permission auth);
//! it is referenced in the schema's `CredentialsEnvelope` comment block
//! and outside the scope of this binding crate.

use core::fmt;

// Generated bindings. `prost-build` writes one file per proto package and
// names it `<package>.rs`; our schema's package is `barista.v1`.
include!(concat!(env!("OUT_DIR"), "/barista.v1.rs"));

// ---------------------------------------------------------------------------
// Redacted `Debug` impls.
// ---------------------------------------------------------------------------
//
// The four types below carry decrypted secret material. Their `Debug`
// representation MUST NOT include the raw bytes — instead we print a
// shape-preserving summary (variant name, byte length, server id) that
// keeps diagnostics useful without leaking the secret.
//
// The plaintext is still reachable via direct field access — these impls
// only protect the `{:?}` formatter. Callers that need the plaintext for a
// legitimate purpose (e.g. composing an HTTP `Authorization` header) read
// the field directly; they MUST NOT route the value through `format!`,
// `Display`, structured logging, or `serde` serialization.

impl fmt::Debug for SshKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("SshKey")
            .field("private_key_pem", &Redacted(self.private_key_pem.len()))
            .field("passphrase", &Redacted(self.passphrase.len()))
            .finish()
    }
}

impl fmt::Debug for credential::Secret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Preserve the variant tag so error messages can say "token-style
        // credential failed" vs "password-style credential failed", but
        // print only the length of the secret material.
        match self {
            Self::Password(p) => f
                .debug_tuple("Secret::Password")
                .field(&Redacted(p.len()))
                .finish(),
            Self::Token(t) => f
                .debug_tuple("Secret::Token")
                .field(&Redacted(t.len()))
                .finish(),
            Self::SshKey(k) => f.debug_tuple("Secret::SshKey").field(k).finish(),
        }
    }
}

impl fmt::Debug for Credential {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // `server_id` is non-sensitive (it's a free-form `<server><id>`
        // from settings.xml) and is *the* useful diagnostic key — print it.
        // `username` is borderline; per the schema comment block,
        // diagnostics should identify the entry by `server_id` only, so
        // redact username length as well.
        f.debug_struct("Credential")
            .field("server_id", &self.server_id)
            .field("username", &Redacted(self.username.len()))
            .field("secret", &self.secret)
            .finish()
    }
}

impl fmt::Debug for CredentialsEnvelope {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Render as the number of entries plus a redacted list of server
        // IDs. Entries-by-server-id is the diagnostic signal callers want
        // ("did the envelope carry the entry I expected?") without ever
        // exposing the underlying secret.
        let ids: Vec<&str> = self.entries.iter().map(|e| e.server_id.as_str()).collect();
        f.debug_struct("CredentialsEnvelope")
            .field("entries.len", &self.entries.len())
            .field("entries[].server_id", &ids)
            .finish()
    }
}

/// `Debug`-only marker that prints `<redacted N bytes>`.
///
/// Used in the manual `Debug` impls above to indicate that a field
/// contains secret material whose byte length is acceptable to surface in
/// diagnostics, but whose contents are not.
struct Redacted(usize);

impl fmt::Debug for Redacted {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "<redacted {} bytes>", self.0)
    }
}
